# Site settings
name: José Pedro Pereira
title: José Pereira | Sysadmin & DevOps Evangelist and SRE Enthusiast
description: Building logical and fast deployment environments based on the best possible solutions for each project.
url: https://komodoro.pt/
baseurl: ''
email: j.pedro.diniz1g@gmail.com
cover: img/og.png
logo: img/emojis/technologist.png
resume: resume.pdf
social:
  - title: email
    url: mailto:j.pedro.diniz1@gmail.com
  - title: twitter
    url: https://twitter.com/freedwaterman
  - title: dev.to
    url: https://dev.to/komodoro
  - title: codepen
    url: https://codepen.io/komodoro
  - title: github
    url: https://github.com/Komodoro/
  - title: linkedin
    url: https://www.linkedin.com/in/pedro-pereira-ig082389isp

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
